export const wheelTypeNames = {
  0: 'Sport',
  1: 'Muscle',
  2: 'Lowrider',
  3: 'SUV',
  4: 'Off-Road',
  5: 'Tuner',
  6: 'Bike',
  7: 'High End',
  8: 'Bennys Original',
  9: 'Bennys Bespoke',
  10: 'OpenWheel',
  11: 'Street',
  12: 'Track',
};
