export const overlays = {
  blemish: {
    max: 23,
    opacity: 0,
    index: 0,
    value: 0,
    hasColor: false,
    firstColor: 0,
  },
  makeup: {
    max: 74,
    opacity: 0,
    index: 4,
    value: 0,
    hasColor: false,
    firstColor: 0,
  },
  ageing: {
    max: 14,
    opacity: 0,
    index: 3,
    value: 0,
    hasColor: false,
    firstColor: 0,
  },
  complexion: {
    max: 11,
    opacity: 0,
    index: 6,
    value: 0,
    hasColor: false,
    firstColor: 0,
  },
  sunDamage: {
    max: 10,
    opacity: 0,
    index: 7,
    value: 0,
    hasColor: false,
    firstColor: 0,
  },
  freckles: {
    max: 17,
    opacity: 0,
    index: 9,
    value: 0,
    hasColor: false,
    firstColor: 0,
  },
  bodyBlemish: {
    max: 11,
    opacity: 0,
    index: 11,
    value: 0,
    hasColor: false,
    firstColor: 0,
  },
  blush: {
    max: 6,
    opacity: 0,
    index: 5,
    value: 0,
    hasColor: true,
    firstColor: 0,
  },
  lipstick: {
    max: 9,
    opacity: 0,
    index: 8,
    value: 0,
    hasColor: true,
    firstColor: 0,
  },
};

export const eyebrowNames = [
  'Balanced',
  'Fashion',
  'Cleopatra',
  'Quizzical',
  'Femme',
  'Seductive',
  'Pinched',
  'Chola',
  'Triomphe',
  'Carefree',
  'Curvaceous',
  'Rodent',
  'Double Tram',
  'Thin',
  'Penciled',
  'Mother Plucker',
  'Straight and Narrow',
  'Natural',
  'Fuzzy',
  'Unkempt',
  'Caterpillar',
  'Regular',
  'Mediterranean',
  'Groomed',
  'Bushels',
  'Feathered',
  'Prickly',
  'Monobrow',
  'Winged',
  'Triple Tram',
  'Arched Tram',
  'Cutouts',
  'Fade Away',
  'Solo Tram',
  'None',
];

export const faceNames = [
  'Benjamin',
  'Daniel',
  'Joshua',
  'Noah',
  'Andrew',
  'Joan',
  'Alex',
  'Isaac',
  'Evan',
  'Ethan',
  'Vincent',
  'Angel',
  'Diego',
  'Adrian',
  'Gabriel',
  'Michael',
  'Santiago',
  'Kevin',
  'Louis',
  'Samuel',
  'Anthony',
  'Hannah',
  'Audrey',
  'Jasmine',
  'Giselle',
  'Amelia',
  'Isabella',
  'Zoe',
  'Ava',
  'Camilla',
  'Violet',
  'Sophia',
  'Eveline',
  'Nicole',
  'Ashley',
  'Grace',
  'Brianna',
  'Natalie',
  'Olivia',
  'Elizabeth',
  'Charlotte',
  'Emma',
  'Claude',
  'Niko',
  'John',
  'Misty',
];

export const facialHairs = [
  'Stubble',
  'Balbo',
  'Circle Beard',
  'Goatee',
  'Chin',
  'Chin Fuzz',
  'Pencil Chin Strap',
  'Scruffy',
  'Musketeer',
  'Mustache',
  'Trimmed Beard',
  'Stubble Beard',
  'Thin Circle Beard',
  'Horseshoe',
  'Pencil and Chops',
  'Chin Strap',
  'Balbo and Sideburns',
  'Mutton Chops',
  'Scruffy Beard',
  'Curly',
  'Curly and Beard',
  'Handlebar',
  'Faustic',
  'Otto and Patch',
  'Otto and Beard',
  'Light Franz',
  'The Hampstead',
  'The Ambrose',
  'Lincoln Curtain',
  'Clean Shaven',
];

export const maleHairs = [
  'Close Shave',
  'Buzzcut',
  'Faux',
  'Hipster',
  'Side',
  'Shorter',
  'Biker',
  'Ponytail',
  'Cornrows',
  'Slicked',
  'Short',
  'Spikey',
  'Caesar',
  'Chopped',
  'Dreads',
  'Long Hair',
  'Shaggy Curls',
  'Surfer Dude',
  'Short Side Part',
  'High Slicked Sides',
  'Long Slicked',
  'Hipster Youth',
  'Mullet',
  'Unknown',
  'Classic Cornrows',
  'Palm Cornrows',
  'Lightning Cornrows',
  'Whipped Cornrows',
  'Zig Zag Cornrows',
  'Snail Cornrows',
  'Hightop',
  'Loose Swept Back',
  'Undercut Swept Back',
  'Undercut Swept Side',
  'Spiked Mohawk',
  'Mod',
  'Layered Mod',
  'Buzzcut',
  'Faux Hawk',
  'Hipster',
  'Side Parting',
  'Shorter Cut',
  'Biker',
  'Ponytail',
  'Cornrows',
  'Slicked',
  'Short Brushed',
  'Spikey',
  'Caesar',
  'Chopped',
  'Dreads',
  'Long Hair',
  'Shaggy Curls Dark Brown',
  'Surfer Dude Dark Brown',
  'Short Side Part Dark Brown',
  'High Slicked Sides Dark Brown',
  'Long Slicked Dark Brown',
  'Hipster Youth Dark Brown',
  'Mullet Dark Brown',
  'Classic Cornrows',
  'Palm Cornrows',
  'Lightning Cornrows',
  'Whipped Cornrows',
  'Zig Zag Cornrows',
  'Snail Cornrows',
  'Hightop',
  'Loose Swept Back',
  'Undercut Swept Back',
  'Undercut Swept Side',
  'Spiked Mohawk',
  'Mod',
  'Layered Mod',
  'Flattop',
  'Military Buzzcut',
  'Impotent Rage',
  'Afro Faded',
  'Top Knot',
  'Two Block',
  'Shaggy Mullet',
  'Short Curls Fade',
  'Curtains',
];

export const femaleHairs = [
  'Close Shave',
  'Short',
  'Layered',
  'Pigtails',
  'Ponytail',
  'Braided ',
  'Braids',
  'Bob',
  'Faux',
  'French',
  'Long Bob',
  'Loose Tied',
  'Pixie ',
  'Shaved Bangs',
  'Top Knot',
  'Wavy Bob',
  'Pin Up Girl',
  'Messy Bun',
  'Flapper Bob',
  'Tight Bun',
  'Twisted Bob',
  'Big Bangs',
  'Braided Top Knot',
  'Mullet',
  'Unknown',
  'Pinched Cornrows',
  'Leaf Cornrows',
  'Zig Zag Cornrows',
  'Pigtail Bangs',
  'Wave Braids',
  'Coil Braids',
  'Rolled Quiff',
  'Loose Swept Back',
  'Undercut Swept Back',
  'Undercut Swept Side',
  'Spiked Mohawk',
  'Bandana and Braid',
  'Skinbyrd',
  'Layered Mod',
  'Short',
  'Layered Bob',
  'Pigtails',
  'Ponytail',
  'Braided Mohawk',
  'Braids',
  'Bob',
  'Faux Hawk',
  'French Twist',
  'Long Bob',
  'Loose Tied',
  'Pixie',
  'Shaved Bangs',
  'Top Knot',
  'Wavy Bob',
  'Messy Bun Chestnut',
  'Pin Up Girl Chestnut',
  'Tight Bun Black',
  'Twisted Bob Chestnut',
  'Flapper Bob Chestnut',
  'Big Bangs Chestnut',
  'Braided Top Knot Chestnut',
  'Mullet Chestnut',
  'Pinched Cornrows',
  'Leaf Cornrows',
  'Zig Zag Cornrows',
  'Pigtail Bangs',
  'Wave Braids',
  'Coil Braids',
  'Rolled Quiff',
  'Loose Swept Back',
  'Undercut Swept Back',
  'Undercut Swept Side',
  'Spiked Mohawk',
  'Bandana and Braid',
  'Layered Mod',
  'Skinbyrd',
  'Neat Bun',
  'Short Bob',
  'Impotent Rage',
  'Afro',
  'Pixie Wavy',
  'Short Tucked Bob',
  'Shaggy Mullet',
  'Buzzcut',
  'Baby Braids',
];

export const hairColors = [
  'Black',
  'Dark Gray',
  'Medium Gray',
  'Darkest Brown',
  'Dark Brown',
  'Brown',
  'Light Brown',
  'Lighter Brown',
  'Lightest Brown',
  'Faded Brown',
  'Faded Blonde',
  'Lightest Blonde',
  'Lighter Blonde',
  'Light Blonde',
  'White Blonde',
  'Grayish Brown',
  'Redish Brown',
  'Red Brown',
  'Dark Red',
  'Red',
  'Very Red',
  'Vibrant Red',
  'Orangeish Red',
  'Faded Red',
  'Faded Orange',
  'Gray',
  'Light Gray',
  'Lighter Gray',
  'Lightest Gray',
  'Dark Purple',
  'Purple',
  'Light Purple',
  'Violet',
  'Vibrant Violet',
  'Candy Pink',
  'Light Pink',
  'Cyan',
  'Blue',
  'Dark Blue',
  'Green',
  'Emerald',
  'Oil Slick',
  'Shiney Green',
  'Vibrant Green',
  'Green',
  'Bleach Blonde',
  'Golden Blonde',
  'Orange Blonde',
  'Orange',
  'Vibrant Orange',
  'Shiny Orange',
  'Dark Orange',
  'Red',
  'Dark Red',
  'Very Dark Red',
  'Black',
  'Black',
  'Black',
  'Black',
  'Black',
];

export const overlayColors = [
  'Red',
  'Pink',
  'Light Pink',
  'Lighter Pink',
  'Lightest Pink',
  'Light Maroon',
  'Maroon',
  'Light Brown',
  'Lighter Brown',
  'Lightest Brown',
  'White Pink',
  'Beige',
  'Brown Red',
  'Orange',
  'Orange Pink',
  'Lightest Pink',
  'Lighter Pink',
  'Pink',
  'Vibrant Pink',
  'Dark Pink',
  'Darker Pink',
  'Darkest Pink',
  'Red',
  'Lighter Red',
  'Vibrant Red',
  'Red Pink',
  'Purple',
  'Light Purple',
  'Dark Purple',
  'Darker Purple',
  'Darkest Purple',
  'Vibrant Purple',
  'Black Purple',
  'Blue',
  'Light Blue',
  'Lighter Blue',
  'Lightest Blue',
  'Cyan',
  'Sea Green',
  'Deep Sea Green',
  'Green',
  'Dark Green',
  'Light Green',
  'Yellow Green',
  'Dark Yellow',
  'Yellow',
  'Yellow Orange',
  'Dark Yellow Orange',
  'Vigrant Orange',
  'Dark Orange',
  'Blonde',
  'Blonde White',
  'White',
  'Gray',
  'Dark Gray',
  'Darkest Gray',
  'Black',
  'Light Blue',
  'Dark Blue',
  'Darkest Blue',
  'Light Brown',
  'Brown',
  'Dark Brown',
  'Darker Brown',
];
